### PR TITLE
Update Fork

### PR DESCRIPTION
**Pull request by S-A-L13**

### CODE REVIEW

**Comment by ner00** [comment]
@S-A-L13 I wonder if you can do something about the personal information included in https://github.com/S-A-L13/snappymail/commit/876ed221c3813b641850683491798c4935b72ec3

I would prefer to not have my e-mail address publicly shared.

Thanks.

**Comment by S-A-L13** [comment]
@ner00 Can't find an e-mail associated with your username. Is it in the code or in the commit comment? Can you tell me the line number it occurs? But I think the problem could be, that even if I remove it or if I update the code, the mail will resist in the former revisions. Or did you know a method how I can remove it completly?

**Comment by ner00** [comment]
@S-A-L13 It's there, at the end of the commit description, before the code changes. That's why I can't give you a line number, just that it's inside your commit description, and I really don't know how it got there, but it did somehow.
````
* Automatically verify S/MIME decrypted signed message

---------

Co-authored-by: the-djmaze <>
Co-authored-by: tinola <>
Co-authored-by: Maarten <>
Co-authored-by: lmperfis <>
Co-authored-by: Sergey Mosin <>
Co-authored-by: hguilbert <>
````

I obviously redacted all the e-mail addresses in the excerpt above.
I don't think you can edit the commit description, but maybe something like a rebase or a hard reset?
It's not so much that the e-mail is a secret since it can be clearly seen in the commit history, it's just that when it's explicitly written into a comment it is indexed by search engines, as was the case. 

Regardless if you can or can't nuke [this commit](https://github.com/S-A-L13/snappymail/commit/876ed221c3813b641850683491798c4935b72ec3), thanks for considering it anyway.

**Comment by S-A-L13** [comment]
@ner00 Yeah ok, I see. Strange thing. Must have been added automatically by the system during the update.
Know what? I'll delete the fork and create a new one if I need it. All my changes were commited to snappymail so I will loose nothing.

**Comment by ner00** [comment]
> PS: Just because I'm interested: How did you find this out? Is there a way to search for such information?

Google :)

**Pull request merged**
